spring.datasource.url=jdbc:sqlite:financas.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# O dialeto default as vezes falha com o boot 3.2.4 para SQLite caso nao referenciado
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta do servidor
server.port=8080
